version: '3.8'

services:
  api:
    build: ./backend
    image: techmentor-backend:latest
    stdin_open: true
    tty: true
    command: ensure_deps php artisan serve --host 0.0.0.0
    ports:
      - "8000:8000"
    volumes:
      - ./backend/:/var/www/html/
    depends_on:
      - mysql

  mysql:
    image: "mysql:8.0"
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    tty: true
    environment:
      MYSQL_DATABASE: techmentor
      MYSQL_ROOT_PASSWORD: techmentor
    volumes:
      - dbdata:/var/lib/mysql/
    ports:
      - "3306:3306"

  frontend:
    build: ./frontend
    image: techmentor-frontend:latest
    stdin_open: true
    tty: true
    command: ensure_deps yarn start
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/:/app/
      - frontend_deps:/app/node_modules/

  frontend_tests:
    build: ./frontend
    image: techmentor-frontend:latest
    environment:
      CI: "true"
    stdin_open: true
    tty: true
    command: ensure_deps yarn test --watchAll
    volumes:
      - ./frontend/:/app/
      - frontend_deps:/app/node_modules/

volumes:
  dbdata:
  frontend_deps:

networks:
  default:
    name: techmentor-backend.local
