version: '3.8'

services:
  app:
    build: .
    image: techmentor-backend:latest
    stdin_open: true
    tty: true
    command: php artisan serve --host 0.0.0.0
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www/html

  mysql:
    image: "mysql:8.0"
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    tty: true
    environment:
      MYSQL_DATABASE: techmentor
      MYSQL_ROOT_PASSWORD: techmentor
    volumes:
      - dbdata:/var/lib/mysql/
    ports:
      - "3306:3306"

volumes:
  dbdata:

networks:
  default:
    name: techmentor-backend.local
