name: Jest

on: push

defaults:
  run:
    working-directory: frontend

jobs:
  jest:
    name: Run the Jest test suite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Build the file
        run: yarn build --if-present
      - name: Run the tests
        run: yarn test
        env:
          CI: true
