name: Lint Code Base

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on: push

jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Codez
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      ################################
      # Setup PHP dependencies #
      ################################
      - name: Laravel setup
        run: |
          cd backend
          composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          VALIDATE_PHP_PSALM: false
          VALIDATE_PHP_PHPSTAN: false
          FILTER_REGEX_EXCLUDE: ".*backend/vendor.*"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
