name: Laravel tests

on: push

defaults:
  run:
    working-directory: backend

jobs:
  larevel-tests:
    name: PHPUnit suite
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        command: mysqld --default-authentication-plugin=mysql_native_password
        env:
          MYSQL_DATABASE: techmentor
          MYSQL_ROOT_PASSWORD: techmentor
        ports:
          - "3306:3306"
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Laravel setup
        run: |
          cp .env.ci .env
          composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
          php artisan key:generate
          chmod -R 777 storage bootstrap/cache
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: techmentor
          DB_PORT: 3306
          DB_USER: root
          DB_PASSWORD: techmentor
        run: |
          php artisan migrate
          vendor/phpunit/phpunit/phpunit
